# Generated by Django 2.0.6 on 2018-09-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='products',
            field=models.ManyToManyField(blank=True, to='productos.Product'),
        ),
    ]
