# Generated by Django 2.0.6 on 2018-09-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='slug',
        ),
    ]
